### ISSUE TITLE
No funciona en 1.18.2 - 40.1.84 forge

### ISSUE THREAD

**Issue by Agartha95** [pixeldreamstudios/MinePop#1]
### Describe the Bug

Hola, cuando usas este mod con la versión 1.18.2 - 40.1.84 de forge, al abrir un mundo, se queda congelado y no funciona y se cierra el juego, solo me funciona en la 40.1.0 o en algunas versiones superiores

### Mod Version

1.8.2 1.5.1

**Comment by kyber-6** [comment]
We cannot help you if you do not provide a crash-log, so please provide one.
Also, we do not speak Spanish, please (at least) translate your report with Google Translate next time.
Thanks!
